#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Forward for Target Distance

Robot Model(s): Modified Squarebot

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          393 Motor             Right side motor, Reversed
Motor Port 3        leftMotor           393 Motor             Left side motor
I2C_1               rightIEM            Integrated Encoder    Encoder mounted on rightMotor
I2C_2               leftIEM             Integrated Encoder    Encoted mounted on leftMotor
----------------------------------------------------------------------------------------------------*/


		// 1 full rotation = 12.56 inch = 1.04feet ( using 627 as target )

		void forwardMovement(int target, int power)
		{
			resetMotorEncoder(rightMotor);
			resetMotorEncoder(leftMotor);

			moveMotorTarget(rightMotor,target,power,true);
			moveMotorTarget(leftMotor,target,power,true);
			wait1Msec(10000);

			 while((getMotorTargetCompleted(rightMotor) == false || getMotorTargetCompleted(leftMotor) == false))
		  {
		  }

		}

		// 90 degree turn = ~ 933 as target

		void turnRobot(int target, int power, int direction)
		{
			resetMotorEncoder(rightMotor);
			resetMotorEncoder(leftMotor);

			if(direction == 1) // left turn
			{
					moveMotorTarget(rightMotor,target,power,true);
					moveMotorTarget(leftMotor,0,0,true);
					wait1Msec(10000);
				 while((getMotorTargetCompleted(rightMotor) == false || getMotorTargetCompleted(leftMotor) == false))
		 		 {

		 		 }
			}else{
							moveMotorTarget(rightMotor,0,0,true);
							moveMotorTarget(leftMotor,target,power,true);
							wait1Msec(10000);
			 			  while((getMotorTargetCompleted(rightMotor) == false || getMotorTargetCompleted(leftMotor) == false))
		 				  {

		  				}
					}

		}

task main()
{

	wait1Msec(2000);

  forwardMovement(2131, 63); //4 straight
  turnRobot(1035, 83, 1);

  forwardMovement(1442, 63);
  turnRobot(1035, 83, 1);

 /* forwardMovement(3135, 63);
  turnRobot(933, 63, 0);
  forwardMovement(1881,63);*/

}
