#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    lineFollowerRIGHT, sensorNone)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in4,    potentiometerSensor, sensorPotentiometer)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Forward for Target Distance

Robot Model(s): Modified Squarebot

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          393 Motor             Right side motor, Reversed
Motor Port 3        leftMotor           393 Motor             Left side motor
I2C_1               rightIEM            Integrated Encoder    Encoder mounted on rightMotor
I2C_2               leftIEM             Integrated Encoder    Encoted mounted on leftMotor
----------------------------------------------------------------------------------------------------*/
/*
	//directional variables for 'turnRobot' function
	const int left = 1;
	const int right =
*/

struct Data
{
		unsigned Forward;
		unsigned Backwards;
		unsigned Left;
		unsigned Right;
		unsigned ArmUp;
		unsigned ArmDn;
		unsigned GripOpen ;
		unsigned GripClose;

};

/*task UARTX_send{

	Data TxPkt;

	char *ptr = (char *)&TxPkt;

	while(true)
	{
		TxPkt.SonarValue = SensorValue(sonarSensor);
		TxPkt.ArmValue = SensorValue(potentiometerSensor);
		//TxPkt.Batt = nImmediateBatteryLevel;

		for(int x=0; x<11; x++)
			sendChar(uartOne, *(ptr+x));

		wait1Msec(5000);  //5 second bursts of data
	}

}*/

task UARTX_recv(){

	Data rcvChar;		//Variable to hold the reciving byte data

	while (true)
	{
		rcvChar = getChar(uartOne);
		if (rcvChar == -1)
		{

			// No character available
	 		wait1Msec(3);
	 		continue;
		}
		if(rcvChar != 0)
		{
			motor[rightMotor] = 65;
			motor[leftMotor] = 65;
		}
	}

}

task main() {

	startTask(UARTX_recv);

}
